#pragma once
#include <d3d9.h>
#include <d3dx9.h>

using D3DXCreateEffect_t = HRESULT(WINAPI*)(LPDIRECT3DDEVICE9,LPCVOID,UINT, CONST D3DXMACRO*, LPD3DXINCLUDE, DWORD, LPD3DXEFFECTPOOL, LPD3DXEFFECT*, LPD3DXBUFFER*);

extern D3DXCreateEffect_t pOrigD3DXCreateEffect;

HRESULT WINAPI MyD3DXCreateEffect(LPDIRECT3DDEVICE9 pDevice, LPCVOID pSrcData, UINT SrcDataLen, CONST D3DXMACRO* pDefines, LPD3DXINCLUDE pInclude, DWORD Flags, LPD3DXEFFECTPOOL pPool, LPD3DXEFFECT* ppEffect, LPD3DXBUFFER* ppCompilationErrors);
